### ISSUE TITLE
Chart.yaml must be must be located at `./`

### ISSUE THREAD

**Issue by siredmar** [eshepelyuk/semantic-release-helm-oci#1]
I am missing a configuratin option where i can specify where the Chart.yaml is located in. Currently This plugin is not usable for my use case, i have several charts that i want to handle, e.g. 

```
./charts/A/
./charts/B/
```

Proposal: Introduce a new parameter called `chartPath` that is used here https://github.com/eshepelyuk/semantic-release-helm-oci/blob/8a66eb11f92e2dd68f532444474b817af76cf78b/lib/prepare.js#L8 and here https://github.com/eshepelyuk/semantic-release-helm-oci/blob/8a66eb11f92e2dd68f532444474b817af76cf78b/lib/publish.js#L8

**Comment by eshepelyuk** [comment]
Hello

For better understanding - if you have 2 charts A and B.

Does it mean that you use `semantic-release` to release both of them ? 

Also, does it mean that you use rhe same `semantic-release` config for releasing both charts ?

**Comment by siredmar** [comment]
You can use this new `chartPath` for option for several use cases. 
To answer your questions: yes, i'd use semantic-release for releasing both charts, and yes, i'd share the same semantic-release config. 

Another super simple scenario would be writing a service and putting the helm chart to to `charts/myservice/`. Using your plugin would not be possible. I hope i answered all your questions. If not don't hesitate asking again :)

**Comment by eshepelyuk** [comment]
Hello

> To answer your questions: yes, i'd use semantic-release for releasing both charts, and yes, i'd share the same semantic-release config.

So, you are not using this atm, but rather `would use`.
That is what I understand from your reply.
Am I right ?

**Comment by siredmar** [comment]
Yes, i am not using this atm but i'd really like to use your plugin. This is the reason i opened this PR. Currently i am testing with a fork and trimming the PR that it is functional working.

**Comment by eshepelyuk** [comment]
Ok, so, having in mind that you are going to have multiple helm charts in a single repo, and the same time you're going to reuse single `semantic-release` config for all of them - I don't understand how this functionality could help ?

Can you explain and show code samples ow can you reuse the single `semantic-release` config to release multiple charts using this plugin ?

**Comment by siredmar** [comment]
Even if i don't release multiple helm charts within one configuration, i don't want to have the `Chart.yaml` in the root of my repo. Does this make sense to you?

**Comment by eshepelyuk** [comment]
No, it does not, since the description of this ssue describes the case of having multiple charts in the same repo .

Please either
* close this issue and open another one with proper description
* or explain me how you can release multiple charts from the same repo using the single semantic-release config using this plugin.
