### ISSUE TITLE
Add chart path

### ISSUE THREAD

**Issue by jbgcarnes** [eshepelyuk/semantic-release-helm-oci#3]
Love the plugin. Currently, the plugin is hard coded to expect the chart at the root of the repository. It would be helpful to allow the user to configure the path to the chart.

Something like chartPath or similar would be helpful if you are still maintaining the project.

**Comment by ievgenii-shepeliuk** [comment]
Hello, 

Unfortunately I am not maintaining the plugin actively, so PR's are welcome.
You can start from here 
https://github.com/eshepelyuk/semantic-release-helm-oci/blob/main/lib/prepare.js#L8
