### ISSUE TITLE
[QUESTION] Do you publish this fork?

### ISSUE THREAD

**Issue by donovanrost** [eshepelyuk/semantic-release-helm-oci#6]
The original version of this isn't maintained. This fork has been updated to include `chartPath`. I would like to use this version. I'm wondering if you publish for consumption?

**Comment by eshepelyuk** [comment]
tbh i don't understand the question.
what fork are you talking about ?

the list of releasefor this plugin is here
https://github.com/eshepelyuk/semantic-release-helm-oci/releases
