### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by eshepelyuk** [eshepelyuk/semantic-release-helm-oci#9]
Because I'm no longer using `semantic-release`, this project will be archived soon.
If anyone interested please feedback in this issue, I'm willing to pass the ownership.

**Comment by jakuboskera** [comment]
Could you please tell me why you are not using `semantic-release`? Is there any better tool? Thanks

**Comment by eshepelyuk** [comment]
> Could you please tell me why you are not using `semantic-release`? Is there any better tool? Thanks

i am using https://github.com/cocogitto/cocogitto
